services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
  # api:
  #   build:
  #     context: api
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./api:/app
  #   ports:
  #     - "3000:3000"
  #     - "2345:2345" # Debugger
  #     - "1433:1433" # SQLLite
  #   environment:
  #     AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
  #     AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  #     AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
  #     AUTH0_CALLBACK_URL: ${AUTH0_CALLBACK_URL}
