name: Clone project to VPS

on:
  pull_request:
    branches: 
    - main

jobs:
  vps_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }} 
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.GIT_REPO_SSH_SECRET }}'
          git checkout ${{ secrets.MAIN_BRANCH }}
          git pull
          docker compose build
          docker compose up
